all: main Server

main: main.o
	clang++ main.o -o main
	
Server: Server.o
	clang++ Server.o -o Server

main.o: main.cpp
	clang++ -c main.cpp

Server.o: Server.cpp
	clang++ -c Server.cpp

clean: 
	rm *.o main Server